### ISSUE TITLE
Deployment using PostGRES

### ISSUE THREAD

**Issue by TomLippincott** [hltcoe/turkle#184] opened 2022-04-30 14:50 UTC
I'm running into a postgres-specific issue like [this one](https://github.com/jazzband/django-oauth-toolkit/issues/714), triggered by the "accept_next_task" view, line 147:

```
len(batch.available_task_ids_for(request.user).select_for_update())
```

Any thoughts?  I'm using a custom User model, but I don't think anything in it would cause this (the error doesn't happen anywhere else when using postgres, or at all when using sqlite).

**Comment by cash** [comment] 2022-04-30 18:47
Duplicate of #152 - unfortunately postgres does not support this query so we need to rewrite it. I put some ideas on that other issue. I'm closing this one as a duplicate.

**Closed by cash** 2022-04-30 18:47 UTC
